name: "MinecraftStats"
description: "Statistics plugin for Minecraft"
author: "Sympatic"
version: "1.1"
api-version: "1.13"
main: org.sympatic.minecraftstats.MinecraftStats
commands:
  stats:
    description: "Stats"
    aliases:
      - profile